queue_rules:
  - name: default
    autoqueue: true
    branch_protection_injection_mode: merge
    queue_conditions:
      - label = enqueue
      - base = main
      - "#approved-reviews-by >= 1"
    merge_method: merge
    checks_timeout: 90 min
    max_checks_retries: 2

merge_queue:
  max_parallel_checks: 1

pull_request_rules:
  - name: Automatically approve Renovate PRs
    conditions:
      - author = altendky-renovate[bot]
    actions:
      review:
        type: APPROVE
