name: Library

on:
  workflow_call:
    outputs:
      matrix:
        description: Matrix configuration as JSON
        value: ${{ jobs.generate.outputs.matrix }}

jobs:
  generate:
    name: Generate library
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.library.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Load library
        id: library
        uses: ./.github/actions/library
