name: Coverage

on:
  workflow_call:

jobs:
  library:
    name: Generate library
    uses: ./.github/workflows/reflow-library.yml

  check:
    name: "\u2602\uFE0F ${{ matrix.os.emoji }} ${{ matrix.arch.emoji }} ${{ matrix.os.name }} ${{ matrix.arch.name }}"
    needs: library
    runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.library.outputs.matrix).axes.os }}
        arch: ${{ fromJSON(needs.library.outputs.matrix).axes.arch }}
        exclude: ${{ fromJSON(needs.library.outputs.matrix).exclude.windows-arm }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4
        env:
          RUSTUP_TOOLCHAIN: stable

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1
        with:
          toolchain: stable
          components: llvm-tools-preview

      - name: Generate coverage
        run: cargo llvm-cov nextest --all-features --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          use_oidc: true
          files: lcov.info
          flags: rust
          fail_ci_if_error: true
